package net.betterthanadventure.updater.backend.instance;

import net.betterthanadventure.updater.LauncherType;
import net.betterthanadventure.updater.backend.IProgressReporter;
import net.betterthanadventure.updater.backend.downloads.Channel;
import net.betterthanadventure.updater.backend.downloads.Downloadable;
import net.betterthanadventure.updater.backend.downloads.Version;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.*;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;
import java.util.jar.JarInputStream;
import java.util.jar.Manifest;

public class InstanceManager {
    private static final @NotNull String INSTANCE_NAME = "BTA_MANAGED_INSTANCE";
    private static final @NotNull String PROPERTIES_FILE_NAME = "bta.properties";
    private static final @NotNull String KEY_VERSION = "bta.version";
    private static final @NotNull String KEY_CHANNEL = "bta.channel";
    private static final @NotNull String WORK_DIR_NAME = "WORK_DIR";

    private final @NotNull File instanceRoot;

    public InstanceManager(final @NotNull LauncherType launcherType) {
        if (launcherType.isMultiMcLike()) {
            this.instanceRoot = new File("../../" + INSTANCE_NAME);
        } else {
            this.instanceRoot = new File(INSTANCE_NAME);
        }
    }

    public File getInstanceRoot() {
        return this.instanceRoot;
    }

    public boolean exists() {
        return this.instanceRoot.exists();
    }

    public final @Nullable String getVersion() {
        if (!exists()) {
            return null;
        }

        // Attempt to load from properties file
        final @Nullable Properties properties = getPropertiesFromFile();
        if (properties != null) {
            final @Nullable String version = properties.getProperty(KEY_VERSION);
            if (version != null) {
                return version;
            }
        }

        // Attempt to read version from jarfile
        final @Nullable Manifest manifest = getManifestFromJar();
        if (manifest != null) {
            final @Nullable String version = manifest.getMainAttributes().getValue("Implementation-Version");
            if (version != null) {
                return "v" + version;
            }
        }

        return null;
    }

    public final @Nullable String getChannel() {
        if (!exists()) {
            return null;
        }

        // Attempt to load from properties file
        final @Nullable Properties properties = getPropertiesFromFile();
        if (properties != null) {
            final @Nullable String channel = properties.getProperty(KEY_CHANNEL);
            if (channel != null) {
                return channel;
            }
        }

        return null;
    }

    public final void synchronize(final @NotNull Channel channel, final @NotNull Version version, final @Nullable IProgressReporter progressReporter) throws IOException {
        if (progressReporter != null) {
            progressReporter.initialize();
        }

        if (!this.instanceRoot.exists()) {
            if (!this.instanceRoot.mkdir()) {
                throw new IOException("Could not create instance directory!");
            }
        }

        final @NotNull File workDir = new File(this.instanceRoot, WORK_DIR_NAME);
        if (!workDir.exists()) {
            if (!workDir.mkdir()) {
                throw new IOException("Could not create working directory!");
            }
        }

        int i = 0;
        for (final @NotNull Downloadable downloadable : version.getDownloadables()) {
            final @NotNull URL downloadableUrl = new URL(version.getUrl(), "auto/" + downloadable.getAssetPath());
            final @NotNull File outFile = new File(workDir, downloadable.getAssetPath());
            if (!outFile.getParentFile().exists()) {
                if (!outFile.getParentFile().mkdirs()) {
                    throw new IOException("Could not create directory for downloadable!");
                }
            }
            try (final @NotNull InputStream stream = downloadableUrl.openStream()) {
                Files.copy(stream, outFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            }
            i++;
            if (progressReporter != null) {
                progressReporter.setProgress((float) i / (float) version.getDownloadables().size());
            }
        }

        // TODO: Copy in place

        final @NotNull Properties btaProperties = new Properties();
        btaProperties.setProperty(KEY_VERSION, version.getId());
        btaProperties.setProperty(KEY_CHANNEL, channel.getId());
        try (final @NotNull Writer writer = new FileWriter(new File(this.instanceRoot, PROPERTIES_FILE_NAME))) {
            btaProperties.store(writer, "Generated by the Better than Adventure! Update Utility. Do not modify!");
        }

        if (progressReporter != null) {
            progressReporter.setDone(true);
        }
    }

    private @Nullable Properties getPropertiesFromFile() {
        final @NotNull Properties properties = new Properties();
        try (final @NotNull FileInputStream stream = new FileInputStream(new File(this.instanceRoot, PROPERTIES_FILE_NAME))) {
            properties.load(stream);
        } catch (final @NotNull IOException ignored) {
            return null;
        }

        return properties;
    }

    private @Nullable Manifest getManifestFromJar() {
        try (final @NotNull JarInputStream stream = new JarInputStream(new FileInputStream(new File(this.instanceRoot, "jarmods/bta.jar")))) {
            return stream.getManifest();
        } catch (IOException e) {
            return null;
        }
    }
}
