package net.betterthanadventure.updater.backend.instance;

import net.betterthanadventure.updater.LauncherType;
import net.betterthanadventure.updater.backend.IProgressReporter;
import net.betterthanadventure.updater.backend.downloads.Channel;
import net.betterthanadventure.updater.backend.downloads.Downloadable;
import net.betterthanadventure.updater.backend.downloads.Version;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.*;
import java.net.URL;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.Comparator;
import java.util.Properties;
import java.util.concurrent.atomic.AtomicReference;
import java.util.jar.JarInputStream;
import java.util.jar.Manifest;

public class InstanceManager {
    private static final @NotNull String INSTANCE_NAME = "BTA_MANAGED_INSTANCE";
    private static final @NotNull String PROPERTIES_FILE_NAME = "bta.properties";
    private static final @NotNull String KEY_VERSION = "bta.version";
    private static final @NotNull String KEY_CHANNEL = "bta.channel";
    private static final @NotNull String WORK_DIR_NAME = "WORK_DIR";

    private final @NotNull LauncherType launcherType;
    private final @NotNull File instanceRoot;

    public InstanceManager(final @NotNull LauncherType launcherType) {
        this.launcherType = launcherType;
        if (launcherType.isMultiMcLike()) {
            this.instanceRoot = new File("../../" + INSTANCE_NAME);
        } else {
            this.instanceRoot = new File(INSTANCE_NAME);
        }
    }

    public File getInstanceRoot() {
        return this.instanceRoot;
    }

    public boolean exists() {
        return this.instanceRoot.exists();
    }

    public final @Nullable String getVersion() {
        if (!exists()) {
            return null;
        }

        // Attempt to load from properties file
        final @Nullable Properties properties = getPropertiesFromFile();
        if (properties != null) {
            final @Nullable String version = properties.getProperty(KEY_VERSION);
            if (version != null) {
                return version;
            }
        }

        // Attempt to read version from jarfile
        final @Nullable Manifest manifest = getManifestFromJar();
        if (manifest != null) {
            final @Nullable String version = manifest.getMainAttributes().getValue("Implementation-Version");
            if (version != null) {
                return "v" + version;
            }
        }

        return null;
    }

    public final @Nullable String getChannel() {
        if (!exists()) {
            return null;
        }

        // Attempt to load from properties file
        final @Nullable Properties properties = getPropertiesFromFile();
        if (properties != null) {
            final @Nullable String channel = properties.getProperty(KEY_CHANNEL);
            if (channel != null) {
                return channel;
            }
        }

        return null;
    }

    public final @NotNull File getWorkDir() {
        return new File(this.instanceRoot, WORK_DIR_NAME);
    }

    public final void synchronize(final @NotNull Channel channel, final @NotNull Version version, final @Nullable IProgressReporter progressReporter) throws IOException {
        if (progressReporter != null) {
            progressReporter.initialize();
        }

        try {
            // Download files
            int i = 0;
            for (final @NotNull Downloadable downloadable : version.getDownloadables()) {
                final @NotNull DownloadableInstaller installer = new DownloadableInstaller(this, version.getUrl(), downloadable);
                installer.synchronize();
                i++;
                if (progressReporter != null) {
                    progressReporter.setProgress((float) i / (float) version.getDownloadables().size());
                }
            }

            // Create properties file
            final @NotNull Properties btaProperties = new Properties();
            btaProperties.setProperty(KEY_VERSION, version.getId());
            btaProperties.setProperty(KEY_CHANNEL, channel.getId());
            final @NotNull File propertiesFile = new File(this.instanceRoot, PROPERTIES_FILE_NAME);
            if (propertiesFile.exists()) {
                final boolean ignored = propertiesFile.delete();
            }
            try (final @NotNull Writer writer = new FileWriter(new File(this.instanceRoot, PROPERTIES_FILE_NAME), false)) {
                btaProperties.store(writer, "Generated by the Better than Adventure! Update Utility. Do not modify!");
            }

            // Refresh instance list
            triggerLauncherRefresh();
        } finally {
            Files.walk(getWorkDir().toPath())
                .sorted(Comparator.reverseOrder())
                .map(Path::toFile)
                .forEach(File::delete);

            if (progressReporter != null) {
                progressReporter.setDone(true);
            }
        }
    }

    private @Nullable Properties getPropertiesFromFile() {
        final @NotNull Properties properties = new Properties();
        try (final @NotNull FileInputStream stream = new FileInputStream(new File(this.instanceRoot, PROPERTIES_FILE_NAME))) {
            properties.load(stream);
        } catch (final @NotNull IOException ignored) {
            return null;
        }

        return properties;
    }

    private @Nullable Manifest getManifestFromJar() {
        try (final @NotNull JarInputStream stream = new JarInputStream(new FileInputStream(new File(this.instanceRoot, "jarmods/bta.jar")))) {
            return stream.getManifest();
        } catch (IOException e) {
            return null;
        }
    }

    private void triggerLauncherRefresh() {
        if (this.launcherType.isMultiMcLike()) {
            final @NotNull File tmpDir = new File("../../temp");
            tmpDir.mkdir();
            tmpDir.delete();
        }
    }
}
