package net.betterthanadventure.updater.backend.instance;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.*;
import java.nio.file.Files;
import java.util.Properties;
import java.util.jar.JarInputStream;
import java.util.jar.Manifest;

public class InstanceProperties {
    private static final @NotNull String PROPERTIES_FILE_NAME = "bta.properties";
    private static final @NotNull String KEY_VERSION = "bta.version";
    private static final @NotNull String KEY_CHANNEL = "bta.channel";

    private final @NotNull InstanceManager instance;
    private @Nullable String channel;
    private @Nullable String version;

    public InstanceProperties(final @NotNull InstanceManager instance) {
        this.instance = instance;
    }

    public @Nullable String getChannel() {
        return this.channel;
    }

    public void setChannel(final @NotNull String channel) {
        this.channel = channel;
    }

    public @Nullable String getVersion() {
        return version;
    }

    public void setVersion(final @NotNull String version) {
        this.version = version;
    }

    public boolean write() {
        final @NotNull File instanceRoot = instance.getInstanceRoot();

        final @NotNull Properties btaProperties = new Properties();
        btaProperties.setProperty(KEY_VERSION, this.version);
        btaProperties.setProperty(KEY_CHANNEL, this.channel);

        final @NotNull File propertiesFile = new File(instanceRoot, PROPERTIES_FILE_NAME);
        if (propertiesFile.exists()) {
            final boolean ignored = propertiesFile.delete();
        }

        try (final @NotNull Writer writer = new FileWriter(new File(instanceRoot, PROPERTIES_FILE_NAME), false)) {
            btaProperties.store(writer, "Generated by the Better than Adventure! Update Utility. Do not modify!");
        } catch (final @NotNull IOException e) {
            return false;
        }

        return true;
    }

    public boolean read(final @Nullable String defaultChannel) {
        return readFromProperties() || (defaultChannel != null && readFromJarfile(defaultChannel));
    }

    private boolean readFromProperties() {
        final @NotNull File instanceRoot = instance.getInstanceRoot();
        if (!instanceRoot.exists()) {
            return false;
        }

        // Load properties file
        final @NotNull Properties properties = new Properties();
        try (final @NotNull InputStream stream = Files.newInputStream(new File(instanceRoot, PROPERTIES_FILE_NAME).toPath())) {
            properties.load(stream);
        } catch (final @NotNull IOException ignored) {
            return false;
        }

        // Attempt to load version and channel from properties
        final @Nullable String version = properties.getProperty(KEY_VERSION);
        final @Nullable String channel = properties.getProperty(KEY_CHANNEL);

        if (version == null || channel == null) {
            return false;
        }

        this.version = version;
        this.channel = channel;

        return true;
    }

    private boolean readFromJarfile(final @NotNull String defaultChannel) {
        final @NotNull File instanceRoot = instance.getInstanceRoot();
        if (!instanceRoot.exists()) {
            return false;
        }

        // Load manifest
        final @NotNull Manifest manifest;
        try (final @NotNull JarInputStream stream = new JarInputStream(Files.newInputStream(new File(instanceRoot, "jarmods/bta.jar").toPath()))) {
            manifest = stream.getManifest();
        } catch (IOException e) {
            return false;
        }

        // Attempt to load version from manifest
        @Nullable String version = manifest.getMainAttributes().getValue("Implementation-Version");
        if (version != null) {
            version = "v" + version;
        }

        if (version == null) {
            return false;
        }

        this.version = version;
        this.channel = defaultChannel;

        return true;
    }
}
